#encoding UTF-8
<div class="entry-content about-outer" itemprop="text">
    <br>
    <h2>Welcome to Lordship Weather</h2>
    <p>This is the website for Letchworth Lordship weather station
	</p>
    <p>The instruments are located on the Lordship Estate in the south-east part of Letchworth Garden City, established as the world's first garden city in 1903.
    </p>The data is provided by an Aercus WeatherSleuth mounted about 2 m above ground in a domestic garden, with three houses about 8 m away.  The data is transmitted  to a Raspberry Pi running <a href="http://www.weewx.com/" target="_blank"> WeeWX</a> and is also uploaded to the <a href="https://wow.metoffice.gov.uk/observations/details/?site_id=3fea8d0c-eeec-e811-a140-0003ff5993a0" target="_blank">Met Office WOW</a> and <a href="https://www.pwsweather.com/station/pws/letchworth/" target=_blank">PWS Weather</a> websites
	<p></p>
    <p>Station Characteristics</p>
    <ul>
        <li>Instruments: <a href=https://www.aercusinstruments.com/aercus-instruments-weathersleuth-professional-ip-weather-station-with-direct-real-time-internet-monitoring/ " target="_blank">Aercus WeatherSleuth</a></li>
        <li>Station hardware: $station.hardware</li>
        <li>Server uptime: $station.os_uptime</li>
        <li>WeeWX uptime: $station.uptime</li>
        <li>WeeWX version: $station.version</li>
        <li>Belchertown Skin Version: $belchertown_version</li>
    </ul>
    <p></p>
    <p></p>
</div>
